# Create Range of Dates with the pd.date_range() Method, Part 3

In [1]:
import pandas as pd
import datetime as dt

In [3]:
pd.date_range(end='1999-12-31', periods=56, freq='D')

DatetimeIndex(['1999-11-06', '1999-11-07', '1999-11-08', '1999-11-09',
               '1999-11-10', '1999-11-11', '1999-11-12', '1999-11-13',
               '1999-11-14', '1999-11-15', '1999-11-16', '1999-11-17',
               '1999-11-18', '1999-11-19', '1999-11-20', '1999-11-21',
               '1999-11-22', '1999-11-23', '1999-11-24', '1999-11-25',
               '1999-11-26', '1999-11-27', '1999-11-28', '1999-11-29',
               '1999-11-30', '1999-12-01', '1999-12-02', '1999-12-03',
               '1999-12-04', '1999-12-05', '1999-12-06', '1999-12-07',
               '1999-12-08', '1999-12-09', '1999-12-10', '1999-12-11',
               '1999-12-12', '1999-12-13', '1999-12-14', '1999-12-15',
               '1999-12-16', '1999-12-17', '1999-12-18', '1999-12-19',
               '1999-12-20', '1999-12-21', '1999-12-22', '1999-12-23',
               '1999-12-24', '1999-12-25', '1999-12-26', '1999-12-27',
               '1999-12-28', '1999-12-29', '1999-12-30', '1999-12-31'],
              dtype='datetime64[ns]', freq='D')

In [4]:
pd.date_range(end='1999-12-31', periods=40, freq='W-SUN')

DatetimeIndex(['1999-03-28', '1999-04-04', '1999-04-11', '1999-04-18',
               '1999-04-25', '1999-05-02', '1999-05-09', '1999-05-16',
               '1999-05-23', '1999-05-30', '1999-06-06', '1999-06-13',
               '1999-06-20', '1999-06-27', '1999-07-04', '1999-07-11',
               '1999-07-18', '1999-07-25', '1999-08-01', '1999-08-08',
               '1999-08-15', '1999-08-22', '1999-08-29', '1999-09-05',
               '1999-09-12', '1999-09-19', '1999-09-26', '1999-10-03',
               '1999-10-10', '1999-10-17', '1999-10-24', '1999-10-31',
               '1999-11-07', '1999-11-14', '1999-11-21', '1999-11-28',
               '1999-12-05', '1999-12-12', '1999-12-19', '1999-12-26'],
              dtype='datetime64[ns]', freq='W-SUN')

In [5]:
pd.date_range(end='1999-12-31', periods=53, freq='MS')

DatetimeIndex(['1995-08-01', '1995-09-01', '1995-10-01', '1995-11-01',
               '1995-12-01', '1996-01-01', '1996-02-01', '1996-03-01',
               '1996-04-01', '1996-05-01', '1996-06-01', '1996-07-01',
               '1996-08-01', '1996-09-01', '1996-10-01', '1996-11-01',
               '1996-12-01', '1997-01-01', '1997-02-01', '1997-03-01',
               '1997-04-01', '1997-05-01', '1997-06-01', '1997-07-01',
               '1997-08-01', '1997-09-01', '1997-10-01', '1997-11-01',
               '1997-12-01', '1998-01-01', '1998-02-01', '1998-03-01',
               '1998-04-01', '1998-05-01', '1998-06-01', '1998-07-01',
               '1998-08-01', '1998-09-01', '1998-10-01', '1998-11-01',
               '1998-12-01', '1999-01-01', '1999-02-01', '1999-03-01',
               '1999-04-01', '1999-05-01', '1999-06-01', '1999-07-01',
               '1999-08-01', '1999-09-01', '1999-10-01', '1999-11-01',
               '1999-12-01'],
              dtype='datetime64[ns]', freq='MS')

In [7]:
pd.date_range(end='2261-12-31', periods=100, freq='7H')

DatetimeIndex(['2261-12-02 03:00:00', '2261-12-02 10:00:00',
               '2261-12-02 17:00:00', '2261-12-03 00:00:00',
               '2261-12-03 07:00:00', '2261-12-03 14:00:00',
               '2261-12-03 21:00:00', '2261-12-04 04:00:00',
               '2261-12-04 11:00:00', '2261-12-04 18:00:00',
               '2261-12-05 01:00:00', '2261-12-05 08:00:00',
               '2261-12-05 15:00:00', '2261-12-05 22:00:00',
               '2261-12-06 05:00:00', '2261-12-06 12:00:00',
               '2261-12-06 19:00:00', '2261-12-07 02:00:00',
               '2261-12-07 09:00:00', '2261-12-07 16:00:00',
               '2261-12-07 23:00:00', '2261-12-08 06:00:00',
               '2261-12-08 13:00:00', '2261-12-08 20:00:00',
               '2261-12-09 03:00:00', '2261-12-09 10:00:00',
               '2261-12-09 17:00:00', '2261-12-10 00:00:00',
               '2261-12-10 07:00:00', '2261-12-10 14:00:00',
               '2261-12-10 21:00:00', '2261-12-11 04:00:00',
               '2261-12-11 11:00:00', '2261-12-11 18:00:00',
               '2261-12-12 01:00:00', '2261-12-12 08:00:00',
               '2261-12-12 15:00:00', '2261-12-12 22:00:00',
               '2261-12-13 05:00:00', '2261-12-13 12:00:00',
               '2261-12-13 19:00:00', '2261-12-14 02:00:00',
               '2261-12-14 09:00:00', '2261-12-14 16:00:00',
               '2261-12-14 23:00:00', '2261-12-15 06:00:00',
               '2261-12-15 13:00:00', '2261-12-15 20:00:00',
               '2261-12-16 03:00:00', '2261-12-16 10:00:00',
               '2261-12-16 17:00:00', '2261-12-17 00:00:00',
               '2261-12-17 07:00:00', '2261-12-17 14:00:00',
               '2261-12-17 21:00:00', '2261-12-18 04:00:00',
               '2261-12-18 11:00:00', '2261-12-18 18:00:00',
               '2261-12-19 01:00:00', '2261-12-19 08:00:00',
               '2261-12-19 15:00:00', '2261-12-19 22:00:00',
               '2261-12-20 05:00:00', '2261-12-20 12:00:00',
               '2261-12-20 19:00:00', '2261-12-21 02:00:00',
               '2261-12-21 09:00:00', '2261-12-21 16:00:00',
               '2261-12-21 23:00:00', '2261-12-22 06:00:00',
               '2261-12-22 13:00:00', '2261-12-22 20:00:00',
               '2261-12-23 03:00:00', '2261-12-23 10:00:00',
               '2261-12-23 17:00:00', '2261-12-24 00:00:00',
               '2261-12-24 07:00:00', '2261-12-24 14:00:00',
               '2261-12-24 21:00:00', '2261-12-25 04:00:00',
               '2261-12-25 11:00:00', '2261-12-25 18:00:00',
               '2261-12-26 01:00:00', '2261-12-26 08:00:00',
               '2261-12-26 15:00:00', '2261-12-26 22:00:00',
               '2261-12-27 05:00:00', '2261-12-27 12:00:00',
               '2261-12-27 19:00:00', '2261-12-28 02:00:00',
               '2261-12-28 09:00:00', '2261-12-28 16:00:00',
               '2261-12-28 23:00:00', '2261-12-29 06:00:00',
               '2261-12-29 13:00:00', '2261-12-29 20:00:00',
               '2261-12-30 03:00:00', '2261-12-30 10:00:00',
               '2261-12-30 17:00:00', '2261-12-31 00:00:00'],
              dtype='datetime64[ns]', freq='7H')