# Changind Options wit hattirbutes and dot syntax

In [7]:
import pandas as pd
import numpy as np

In [3]:
data = np.random.randint(0,100,[1000,50])

In [5]:
data

array([[93, 24, 22, ..., 69, 75, 62],
       [62, 96, 53, ..., 96, 18, 63],
       [22, 71, 84, ...,  2, 41, 44],
       ...,
       [89, 64, 10, ..., 27, 23,  5],
       [42, 71, 61, ...,  9, 61,  0],
       [88, 98,  0, ..., 11, 99, 97]])

In [10]:
df = pd.DataFrame(data)
df.head(n=2)

,0,1,2,3,4,5,6,7,8,9,...,40,41,42,43,44,45,46,47,48,49
0,93,24,22,63,87,99,86,31,45,6,...,60,75,29,8,60,65,41,69,75,62
1,62,96,53,73,83,63,50,58,15,99,...,8,15,21,18,99,52,42,96,18,63

In [11]:
pd.options.display.max_rows

60

In [12]:
pd.options.display.max_rows = 69

In [13]:
pd.options.display.max_rows

69

In [14]:
df

,0,1,2,3,4,5,6,7,8,9,...,40,41,42,43,44,45,46,47,48,49
0,93,24,22,63,87,99,86,31,45,6,...,60,75,29,8,60,65,41,69,75,62
1,62,96,53,73,83,63,50,58,15,99,...,8,15,21,18,99,52,42,96,18,63
2,22,71,84,55,26,34,6,2,3,52,...,24,68,39,1,27,74,42,2,41,44
3,54,30,37,69,76,31,89,12,63,22,...,80,50,94,82,34,87,9,13,13,7
4,82,73,74,50,33,56,65,39,18,98,...,45,75,12,41,19,89,29,67,84,61
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,37,47,99,99,82,24,48,80,33,68,...,36,28,24,45,19,14,66,6,7,18
996,43,34,16,21,68,5,69,71,99,41,...,89,22,21,94,22,35,20,63,10,21
997,89,64,10,85,32,58,46,14,55,15,...,25,30,78,52,42,34,5,27,23,5
998,42,71,61,58,63,5,17,40,31,61,...,21,32,99,16,70,98,80,9,61,0
999,88,98,0,98,19,24,82,71,36,32,...,24,88,61,57,55,73,67,11,99,97

In [15]:
pd.options.display.max_rows

69

In [16]:
df

,0,1,2,3,4,5,6,7,8,9,...,40,41,42,43,44,45,46,47,48,49
0,93,24,22,63,87,99,86,31,45,6,...,60,75,29,8,60,65,41,69,75,62
1,62,96,53,73,83,63,50,58,15,99,...,8,15,21,18,99,52,42,96,18,63
2,22,71,84,55,26,34,6,2,3,52,...,24,68,39,1,27,74,42,2,41,44
3,54,30,37,69,76,31,89,12,63,22,...,80,50,94,82,34,87,9,13,13,7
4,82,73,74,50,33,56,65,39,18,98,...,45,75,12,41,19,89,29,67,84,61
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,37,47,99,99,82,24,48,80,33,68,...,36,28,24,45,19,14,66,6,7,18
996,43,34,16,21,68,5,69,71,99,41,...,89,22,21,94,22,35,20,63,10,21
997,89,64,10,85,32,58,46,14,55,15,...,25,30,78,52,42,34,5,27,23,5
998,42,71,61,58,63,5,17,40,31,61,...,21,32,99,16,70,98,80,9,61,0
999,88,98,0,98,19,24,82,71,36,32,...,24,88,61,57,55,73,67,11,99,97

In [17]:
pd.options.display.max_rows = 5

In [18]:
df

,0,1,2,3,4,5,6,7,8,9,...,40,41,42,43,44,45,46,47,48,49
0,93,24,22,63,87,99,86,31,45,6,...,60,75,29,8,60,65,41,69,75,62
1,62,96,53,73,83,63,50,58,15,99,...,8,15,21,18,99,52,42,96,18,63
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
998,42,71,61,58,63,5,17,40,31,61,...,21,32,99,16,70,98,80,9,61,0
999,88,98,0,98,19,24,82,71,36,32,...,24,88,61,57,55,73,67,11,99,97

In [19]:
pd.options.display.max_rows = 15

In [20]:
df

,0,1,2,3,4,5,6,7,8,9,...,40,41,42,43,44,45,46,47,48,49
0,93,24,22,63,87,99,86,31,45,6,...,60,75,29,8,60,65,41,69,75,62
1,62,96,53,73,83,63,50,58,15,99,...,8,15,21,18,99,52,42,96,18,63
2,22,71,84,55,26,34,6,2,3,52,...,24,68,39,1,27,74,42,2,41,44
3,54,30,37,69,76,31,89,12,63,22,...,80,50,94,82,34,87,9,13,13,7
4,82,73,74,50,33,56,65,39,18,98,...,45,75,12,41,19,89,29,67,84,61
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,37,47,99,99,82,24,48,80,33,68,...,36,28,24,45,19,14,66,6,7,18
996,43,34,16,21,68,5,69,71,99,41,...,89,22,21,94,22,35,20,63,10,21
997,89,64,10,85,32,58,46,14,55,15,...,25,30,78,52,42,34,5,27,23,5
998,42,71,61,58,63,5,17,40,31,61,...,21,32,99,16,70,98,80,9,61,0
999,88,98,0,98,19,24,82,71,36,32,...,24,88,61,57,55,73,67,11,99,97

In [21]:
pd.options.display.max_rows = 20

In [22]:
df

,0,1,2,3,4,5,6,7,8,9,...,40,41,42,43,44,45,46,47,48,49
0,93,24,22,63,87,99,86,31,45,6,...,60,75,29,8,60,65,41,69,75,62
1,62,96,53,73,83,63,50,58,15,99,...,8,15,21,18,99,52,42,96,18,63
2,22,71,84,55,26,34,6,2,3,52,...,24,68,39,1,27,74,42,2,41,44
3,54,30,37,69,76,31,89,12,63,22,...,80,50,94,82,34,87,9,13,13,7
4,82,73,74,50,33,56,65,39,18,98,...,45,75,12,41,19,89,29,67,84,61
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,37,47,99,99,82,24,48,80,33,68,...,36,28,24,45,19,14,66,6,7,18
996,43,34,16,21,68,5,69,71,99,41,...,89,22,21,94,22,35,20,63,10,21
997,89,64,10,85,32,58,46,14,55,15,...,25,30,78,52,42,34,5,27,23,5
998,42,71,61,58,63,5,17,40,31,61,...,21,32,99,16,70,98,80,9,61,0
999,88,98,0,98,19,24,82,71,36,32,...,24,88,61,57,55,73,67,11,99,97

In [23]:
pd.options.display.max_columns

20

In [24]:
pd.options.display.max_columns = 5

In [25]:
df

     0   1   ...  48  49
0    93  24  ...  75  62
1    62  96  ...  18  63
2    22  71  ...  41  44
3    54  30  ...  13   7
4    82  73  ...  84  61
..   ..  ..  ...  ..  ..
995  37  47  ...   7  18
996  43  34  ...  10  21
997  89  64  ...  23   5
998  42  71  ...  61   0
999  88  98  ...  99  97

[1000 rows x 50 columns]

In [26]:
pd.options.display.max_columns = 21

In [27]:
df

,0,1,2,3,4,5,6,7,8,9,...,40,41,42,43,44,45,46,47,48,49
0,93,24,22,63,87,99,86,31,45,6,...,60,75,29,8,60,65,41,69,75,62
1,62,96,53,73,83,63,50,58,15,99,...,8,15,21,18,99,52,42,96,18,63
2,22,71,84,55,26,34,6,2,3,52,...,24,68,39,1,27,74,42,2,41,44
3,54,30,37,69,76,31,89,12,63,22,...,80,50,94,82,34,87,9,13,13,7
4,82,73,74,50,33,56,65,39,18,98,...,45,75,12,41,19,89,29,67,84,61
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,37,47,99,99,82,24,48,80,33,68,...,36,28,24,45,19,14,66,6,7,18
996,43,34,16,21,68,5,69,71,99,41,...,89,22,21,94,22,35,20,63,10,21
997,89,64,10,85,32,58,46,14,55,15,...,25,30,78,52,42,34,5,27,23,5
998,42,71,61,58,63,5,17,40,31,61,...,21,32,99,16,70,98,80,9,61,0
999,88,98,0,98,19,24,82,71,36,32,...,24,88,61,57,55,73,67,11,99,97

In [28]:
pd.options.display.max_columns = 55

In [29]:
df

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49
0,93,24,22,63,87,99,86,31,45,6,32,60,72,54,76,24,59,71,80,36,93,64,16,85,5,8,50,54,27,37,49,39,67,96,17,66,22,12,86,99,60,75,29,8,60,65,41,69,75,62
1,62,96,53,73,83,63,50,58,15,99,76,58,20,80,64,4,60,35,5,27,81,98,74,93,33,1,48,3,2,56,76,19,46,5,35,30,33,61,2,34,8,15,21,18,99,52,42,96,18,63
2,22,71,84,55,26,34,6,2,3,52,89,53,96,70,20,65,86,67,38,31,54,82,40,5,60,84,29,92,50,50,26,79,39,65,21,88,71,1,59,5,24,68,39,1,27,74,42,2,41,44
3,54,30,37,69,76,31,89,12,63,22,16,73,95,17,22,51,95,59,45,34,67,59,56,99,67,18,74,39,27,72,0,13,60,31,30,47,40,58,3,9,80,50,94,82,34,87,9,13,13,7
4,82,73,74,50,33,56,65,39,18,98,90,42,2,27,35,70,32,26,80,80,70,67,1,78,92,85,28,59,49,39,34,5,59,75,70,26,39,40,26,24,45,75,12,41,19,89,29,67,84,61
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,37,47,99,99,82,24,48,80,33,68,70,24,89,73,16,40,9,34,15,52,2,29,81,38,98,63,69,40,26,98,73,54,15,95,51,76,72,18,8,71,36,28,24,45,19,14,66,6,7,18
996,43,34,16,21,68,5,69,71,99,41,75,6,85,20,99,1,61,13,91,82,54,87,12,19,92,36,76,70,16,41,44,87,14,89,81,78,20,14,19,7,89,22,21,94,22,35,20,63,10,21
997,89,64,10,85,32,58,46,14,55,15,45,44,76,38,57,86,0,82,89,10,3,66,36,79,73,58,34,46,31,2,16,82,88,0,65,90,68,62,64,46,25,30,78,52,42,34,5,27,23,5
998,42,71,61,58,63,5,17,40,31,61,17,16,90,79,65,78,60,39,91,44,41,91,26,82,5,95,49,29,94,21,18,2,65,47,51,86,71,33,98,59,21,32,99,16,70,98,80,9,61,0
999,88,98,0,98,19,24,82,71,36,32,76,84,88,85,67,3,25,28,45,68,94,0,29,85,70,87,59,75,15,18,12,6,42,71,67,13,73,70,8,81,24,88,61,57,55,73,67,11,99,97

In [30]:
pd.options.display.max_columns = 25

In [31]:
df

,0,1,2,3,4,5,6,7,8,9,10,11,...,38,39,40,41,42,43,44,45,46,47,48,49
0,93,24,22,63,87,99,86,31,45,6,32,60,...,86,99,60,75,29,8,60,65,41,69,75,62
1,62,96,53,73,83,63,50,58,15,99,76,58,...,2,34,8,15,21,18,99,52,42,96,18,63
2,22,71,84,55,26,34,6,2,3,52,89,53,...,59,5,24,68,39,1,27,74,42,2,41,44
3,54,30,37,69,76,31,89,12,63,22,16,73,...,3,9,80,50,94,82,34,87,9,13,13,7
4,82,73,74,50,33,56,65,39,18,98,90,42,...,26,24,45,75,12,41,19,89,29,67,84,61
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,37,47,99,99,82,24,48,80,33,68,70,24,...,8,71,36,28,24,45,19,14,66,6,7,18
996,43,34,16,21,68,5,69,71,99,41,75,6,...,19,7,89,22,21,94,22,35,20,63,10,21
997,89,64,10,85,32,58,46,14,55,15,45,44,...,64,46,25,30,78,52,42,34,5,27,23,5
998,42,71,61,58,63,5,17,40,31,61,17,16,...,98,59,21,32,99,16,70,98,80,9,61,0
999,88,98,0,98,19,24,82,71,36,32,76,84,...,8,81,24,88,61,57,55,73,67,11,99,97